name: prolab
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: 4.6.5
  hexcolor: ^3.0.1
  flutter_neumorphic: ^3.0.3
  http: ^0.13.4
  provider: ^6.0.1
  google_fonts: ^2.1.0
  file_picker: ^5.2.2
 

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
